INSERT INTO public."AssayBarcode"( id, "barcode", "tubeNum", "type")
VALUES 
(uuid_generate_v4(),'ATC','1','8 Assays'),
(uuid_generate_v4(),'TGA','2','8 Assays'),
(uuid_generate_v4(),'GCT','3','8 Assays'),
(uuid_generate_v4(),'CAG','4','8 Assays'),
(uuid_generate_v4(),'AGA','5','8 Assays'),
(uuid_generate_v4(),'TCT','6','8 Assays'),
(uuid_generate_v4(),'GAG','7','8 Assays'),
(uuid_generate_v4(),'CTC','8','8 Assays'),
(uuid_generate_v4(),'CATC','1','12 Assays'),
(uuid_generate_v4(),'ATGA','2','12 Assays'),
(uuid_generate_v4(),'AGCT','3','12 Assays'),
(uuid_generate_v4(),'ACAG','4','12 Assays'),
(uuid_generate_v4(),'GAAT','5','12 Assays'),
(uuid_generate_v4(),'TACG','6','12 Assays'),
(uuid_generate_v4(),'TTAC','7','12 Assays'),
(uuid_generate_v4(),'GTTG','8','12 Assays'),
(uuid_generate_v4(),'CCGT','9','12 Assays'),
(uuid_generate_v4(),'CGAA','10','12 Assays'),
(uuid_generate_v4(),'TCTA','11','12 Assays'),
(uuid_generate_v4(),'GGGC','12','12 Assays');