-- UPDATE public."I5Primer"
-- 	SET libtype='any', protocol='Split&Pool', seq3='', seq4='', "subProtocol"='12 Assays'


INSERT INTO public."I5Primer"( id, "fSeq", "rcSeq",  "seq3", "seq4", "libtype",  "subProtocol", "protocol","createdAt" )
VALUES 
-- ('D501','TATAGCCT','AGGCTATA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('D502','ATAGAGGC','GCCTCTAT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('D503','CCTATCCT','AGGATAGG', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('D504','GGCTCTGA','TCAGAGCC', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('D505','AGGCGAAG','CTTCGCCT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('D506','TAATCTTA','TAAGATTA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('N503','TATCCTCT','AGAGGATA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('N504','AGAGTAGA','TCTACTCT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('N505','GTAAGGAG','CTCCTTAC', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('N506','ACTGCATA','TATGCAGT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('N507','AAGGAGTA','TACTCCTT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('N508','CTAAGCCT','AGGCTTAG', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),

-- ('[E/H/N/S]501','TAGATCGC','GCGATCTA', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
-- ('[E/H/N/S]502','CTCTCTAT','ATAGAGAG', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
-- ('[E/H/N/S]503','TATCCTCT','AGAGGATA', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
-- ('[E/H/N/S]504','AGAGTAGA','TCTACTCT', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
-- ('[E/H/N/S]505','GTAAGGAG','CTCCTTAC', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
-- ('[E/H/N/S]506','ACTGCATA','TATGCAGT', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
-- ('[E/H/N/S]507','AAGGAGTA','TACTCCTT', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
-- ('[E/H/N/S]508','CTAAGCCT','AGGCTTAG', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),


-- ('SI-TT-A1','AGTGTTACCT','AGGTAACACT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A2','GCCAACCCTG','CAGGGTTGGC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A3','TTAGACTGAT','ATCAGTCTAA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A4','TATCTTCATC','GATGAAGATA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A5','GAGCATCTAT','ATAGATGCTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A6','CCCTAACTTC','GAAGTTAGGG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A7','TACTACCTTT','AAAGGTAGTA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A8','GAACTTGGAG','CTCCAAGTTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A9','TTCCTGTTAC','GTAACAGGAA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A10','ATGGTCTAAA','TTTAGACCAT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A11','GATTCGAGGA','TCCTCGAATC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-A12','GACTGTCAAT','ATTGACAGTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B1','ACAGTTCGTT','AACGAACTGT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B2','CGGGAGAGTC','GACTCTCCCG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B3','GTTCGTCACA','TGTGACGAAC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B4','CTAGTGTGGT','ACCACACTAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B5','CCGATGGTCT','AGACCATCGG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B6','TACGTAATGC','GCATTACGTA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B7','CCAACGATTT','AAATCGTTGG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B8','TATGCGTGAA','TTCACGCATA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B9','CAGGTAAGTG','CACTTACCTG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B10','AATCGTCTAG','CTAGACGATT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B11','TGACCTCTAG','CTAGAGGTCA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-B12','TAGGTCACTC','GAGTGACCTA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C1','CAAGGATAAA','TTTATCCTTG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C2','CCGAGTAGTA','TACTACTCGG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C3','GAATGTTGTG','CACAACATTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C4','TGTCGGGCAC','GTGCCCGACA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C5','ACGTTCTCGC','GCGAGAACGT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C6','ACGACCCTAA','TTAGGGTCGT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C7','CCTGTATTCT','AGAATACAGG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C8','CACGTGCCCT','AGGGCACGTG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C9','GTTTCGTCCT','AGGACGAAAC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C10','GAGGGTGGGA','TCCCACCCTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C11','CTTGGGAATT','AATTCCCAAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-C12','GCAACTCAGG','CCTGAGTTGC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D1','GCTTGTCGAA','TTCGACAAGC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D2','CACCTCGGGT','ACCCGAGGTG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D3','AATACAACGA','TCGTTGTATT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D4','TTCCGTGCAC','GTGCACGGAA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D5','GTGGCAGGAG','CTCCTGCCAC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D6','GACACCAAAC','GTTTGGTGTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D7','AGCCCGTAAC','GTTACGGGCT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D8','AGGTGTCTGC','GCAGACACCT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D9','CCTCTGGCGT','ACGCCAGAGG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D10','ACAAGTGTCG','CGACACTTGT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D11','CTGGAAGCAA','TTGCTTCCAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-D12','ACTCTAGTAG','CTACTAGAGT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E1','CTGTCCTGCT','AGCAGGACAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E2','ATAACCCATT','AATGGGTTAT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E3','AGGAACTAGG','CCTAGTTCCT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E4','ATTCAGGTTA','TAACCTGAAT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E5','CAGGATGTTG','CAACATCCTG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E6','AACCTGGTAG','CTACCAGGTT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E7','TCATGCACAG','CTGTGCATGA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E8','ATTGACTTGG','CCAAGTCAAT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E9','TCGATGTCCA','TGGACATCGA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E10','ATATCCACAA','TTGTGGATAT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E11','GTGAATGCCA','TGGCATTCAC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-E12','CATTCATGAC','GTCATGAATG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F1','AGCGGGATTT','AAATCCCGCT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F2','CTGATTCCTC','GAGGAATCAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F3','TTGAAATGGG','CCCATTTCAA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F4','ACCTCCGCTT','AAGCGGAGGT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F5','TGATAAGCAC','GTGCTTATCA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F6','GCGTGAGATT','AATCTCACGC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F7','AATGAGCTTA','TAAGCTCATT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F8','GACATAGCTC','GAGCTATGTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F9','CGAACGTGAC','GTCACGTTCG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F10','CGGTTTAACA','TGTTAAACCG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F11','TAGTGTACAC','GTGTACACTA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-F12','CTATGAACAT','ATGTTCATAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G1','CTTGATCGTA','TACGATCAAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G2','GATTCCTTTA','TAAAGGAATC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G3','AGGTCAGGAT','ATCCTGACCT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G4','GCCTGGCTAG','CTAGCCAGGC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G5','TGCATCGAGT','ACTCGATGCA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G6','TAGCACTAAG','CTTAGTGCTA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G7','TTCGGCCAAA','TTTGGCCGAA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G8','CTATACTCAA','TTGAGTATAG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G9','TGCGGATGTT','AACATCCGCA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G10','TGAACGCCCT','AGGGCGTTCA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G11','CATTAGAAAC','GTTTCTAATG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-G12','ATCAGGGCTT','AAGCCCTGAT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H1','CGTACCGTTA','TAACGGTACG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H2','CGGCTCTGTC','GACAGAGCCG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H3','GACGGATTGG','CCAATCCGTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H4','TGCCACACAG','CTGTGTGGCA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H5','TTGTGTTTCT','AGAAACACAA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H6','GAATACTAAC','GTTAGTATTC','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H7','TGTGTTCGAT','ATCGAACACA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H8','ATAGATAGGG','CCCTATCTAT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H9','CGAGTCCTTT','AAAGGACTCG','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H10','AAAGGCTCTA','TAGAGCCTTT','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H11','TGACGGAATG','CATTCCGTCA','','','rna','10x','Droplet',NOW()),
-- ('SI-TT-H12','GTAGGAGTCG','CGACTCCTAC','','','rna','10x','Droplet',NOW()),



('SI-TT-A1','AGTGTTACCT','AGGTAACACT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A2','GCCAACCCTG','CAGGGTTGGC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A3','TTAGACTGAT','ATCAGTCTAA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A4','TATCTTCATC','GATGAAGATA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A5','GAGCATCTAT','ATAGATGCTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A6','CCCTAACTTC','GAAGTTAGGG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A7','TACTACCTTT','AAAGGTAGTA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A8','GAACTTGGAG','CTCCAAGTTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A9','TTCCTGTTAC','GTAACAGGAA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A10','ATGGTCTAAA','TTTAGACCAT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A11','GATTCGAGGA','TCCTCGAATC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-A12','GACTGTCAAT','ATTGACAGTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B1','ACAGTTCGTT','AACGAACTGT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B2','CGGGAGAGTC','GACTCTCCCG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B3','GTTCGTCACA','TGTGACGAAC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B4','CTAGTGTGGT','ACCACACTAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B5','CCGATGGTCT','AGACCATCGG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B6','TACGTAATGC','GCATTACGTA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B7','CCAACGATTT','AAATCGTTGG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B8','TATGCGTGAA','TTCACGCATA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B9','CAGGTAAGTG','CACTTACCTG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B10','AATCGTCTAG','CTAGACGATT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B11','TGACCTCTAG','CTAGAGGTCA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-B12','TAGGTCACTC','GAGTGACCTA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C1','CAAGGATAAA','TTTATCCTTG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C2','CCGAGTAGTA','TACTACTCGG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C3','GAATGTTGTG','CACAACATTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C4','TGTCGGGCAC','GTGCCCGACA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C5','ACGTTCTCGC','GCGAGAACGT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C6','ACGACCCTAA','TTAGGGTCGT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C7','CCTGTATTCT','AGAATACAGG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C8','CACGTGCCCT','AGGGCACGTG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C9','GTTTCGTCCT','AGGACGAAAC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C10','GAGGGTGGGA','TCCCACCCTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C11','CTTGGGAATT','AATTCCCAAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-C12','GCAACTCAGG','CCTGAGTTGC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D1','GCTTGTCGAA','TTCGACAAGC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D2','CACCTCGGGT','ACCCGAGGTG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D3','AATACAACGA','TCGTTGTATT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D4','TTCCGTGCAC','GTGCACGGAA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D5','GTGGCAGGAG','CTCCTGCCAC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D6','GACACCAAAC','GTTTGGTGTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D7','AGCCCGTAAC','GTTACGGGCT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D8','AGGTGTCTGC','GCAGACACCT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D9','CCTCTGGCGT','ACGCCAGAGG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D10','ACAAGTGTCG','CGACACTTGT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D11','CTGGAAGCAA','TTGCTTCCAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-D12','ACTCTAGTAG','CTACTAGAGT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E1','CTGTCCTGCT','AGCAGGACAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E2','ATAACCCATT','AATGGGTTAT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E3','AGGAACTAGG','CCTAGTTCCT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E4','ATTCAGGTTA','TAACCTGAAT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E5','CAGGATGTTG','CAACATCCTG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E6','AACCTGGTAG','CTACCAGGTT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E7','TCATGCACAG','CTGTGCATGA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E8','ATTGACTTGG','CCAAGTCAAT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E9','TCGATGTCCA','TGGACATCGA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E10','ATATCCACAA','TTGTGGATAT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E11','GTGAATGCCA','TGGCATTCAC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-E12','CATTCATGAC','GTCATGAATG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F1','AGCGGGATTT','AAATCCCGCT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F2','CTGATTCCTC','GAGGAATCAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F3','TTGAAATGGG','CCCATTTCAA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F4','ACCTCCGCTT','AAGCGGAGGT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F5','TGATAAGCAC','GTGCTTATCA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F6','GCGTGAGATT','AATCTCACGC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F7','AATGAGCTTA','TAAGCTCATT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F8','GACATAGCTC','GAGCTATGTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F9','CGAACGTGAC','GTCACGTTCG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F10','CGGTTTAACA','TGTTAAACCG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F11','TAGTGTACAC','GTGTACACTA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-F12','CTATGAACAT','ATGTTCATAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G1','CTTGATCGTA','TACGATCAAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G2','GATTCCTTTA','TAAAGGAATC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G3','AGGTCAGGAT','ATCCTGACCT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G4','GCCTGGCTAG','CTAGCCAGGC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G5','TGCATCGAGT','ACTCGATGCA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G6','TAGCACTAAG','CTTAGTGCTA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G7','TTCGGCCAAA','TTTGGCCGAA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G8','CTATACTCAA','TTGAGTATAG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G9','TGCGGATGTT','AACATCCGCA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G10','TGAACGCCCT','AGGGCGTTCA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G11','CATTAGAAAC','GTTTCTAATG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-G12','ATCAGGGCTT','AAGCCCTGAT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H1','CGTACCGTTA','TAACGGTACG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H2','CGGCTCTGTC','GACAGAGCCG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H3','GACGGATTGG','CCAATCCGTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H4','TGCCACACAG','CTGTGTGGCA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H5','TTGTGTTTCT','AGAAACACAA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H6','GAATACTAAC','GTTAGTATTC','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H7','TGTGTTCGAT','ATCGAACACA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H8','ATAGATAGGG','CCCTATCTAT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H9','CGAGTCCTTT','AAAGGACTCG','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H10','AAAGGCTCTA','TAGAGCCTTT','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H11','TGACGGAATG','CATTCCGTCA','','','rna','10x 2BMulti','Droplet',NOW()),
('SI-TT-H12','GTAGGAGTCG','CGACTCCTAC','','','rna','10x 2BMulti','Droplet',NOW());
