INSERT INTO public."I5Primer"( id, "fSeq", "rcSeq", "createdAt")
VALUES 
('D501','TATAGCCT','AGGCTATA',NOW()),
('D502','ATAGAGGC','GCCTCTAT',NOW()),
('D503','CCTATCCT','AGGATAGG',NOW()),
('D504','GGCTCTGA','TCAGAGCC',NOW()),
('D505','AGGCGAAG','CTTCGCCT',NOW()),
('D506','TAATCTTA','TAAGATTA',NOW()),
('N503','TATCCTCT','AGAGGATA',NOW()),
('N504','AGAGTAGA','TCTACTCT',NOW()),
('N505','GTAAGGAG','CTCCTTAC',NOW()),
('N506','ACTGCATA','TATGCAGT',NOW()),
('N507','AAGGAGTA','TACTCCTT',NOW()),
('N508','CTAAGCCT','AGGCTTAG',NOW());
