UPDATE public."I7Primer"
	SET libtype='any', protocol='Split&Pool', seq3='', seq4='', "subProtocol"='12 Assays'


INSERT INTO public."I7Primer"( id, "fSeq", "rcSeq",  "seq3", "seq4", "libtype",  "subProtocol", "protocol","createdAt" )
VALUES 
-- ('A001','CGTGAT','ATCACG', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A002','ACATCG','CGATGT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A003','GCCTAA','TTAGGC', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A004','TGGTCA','TGACCA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A005','CACTGT','ACAGTG', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A006','ATTGGC','GCCAAT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A007','GATCTG','CAGATC', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A008','TCAAGT','ACTTGA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A009','CTGATC','GATCAG', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A010','AAGCTA','TAGCTT', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A011','GTAGCC','GGCTAC', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A012','TACAAG','CTTGTA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A013','TTGACT','AGTCAA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A014','GGAACT','AGTTCC', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A015','TGACAT','ATGTCA', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),
-- ('A016','GGACGG','CCGTCC', '', '', 'any', '12 Assays', 'Split&Pool',NOW()),

('[H/N]701','TCGCCTTA','TAAGGCGA', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]702','CTAGTACG','CGTACTAG', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]703','TTCTGCCT','AGGCAGAA', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]704','GCTCAGGA','TCCTGAGC', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]705','AGGAGTCC','GGACTCCT', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]706','CATGCCTA','TAGGCATG', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]707','GTAGAGAG','CTCTCTAC', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]708','CCTCTCTG','CAGAGAGG', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]709','AGCGTAGC','GCTACGCT', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]710','CAGCCTCG','CGAGGCTG', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]711','TGCCTCTT','AAGAGGCA', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),
('[H/N]712','TCCTCTAC','GTAGAGGA', '', '', 'any', 'Cut&Tag', 'Bulk',NOW()),

('SI-NA-A1','AAACGGCG','CCTACCAT','GGCGTTTC','TTGTAAGA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B1','AGGCTACC','CTAGCTGT','GCCAACAA','TATTGGTG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C1','AGACTTTC','CCGAGGCA','GATGCAGT','TTCTACAG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D1','AGCTGCGT','CAACCATC','GTGGAGCA','TCTATTAG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E1','ACGAAAGC','CGCCCGTA','GTTTGCCT','TAAGTTAG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F1','ATCGCTCC','CCGTACAG','GATAGGTA','TGACTAGT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G1','ATGCGATT','CATATGCG','GGATACGA','TCCGCTAC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H1','AAACTCAT','CGGGAGTA','GTCACAGG','TCTTGTCC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A2','AGCCCTTT','CAAGTCCA','GTGAGAAG','TCTTAGGC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B2','AAGTTGAT','CCCACCCA','GGTCGAGC','TTAGATTG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C2','AATCACTA','CCGAGAAC','GTAGTGCG','TGCTCTGT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D2','ACATTCCG','CTGCGGTA','GACACAAT','TGTGATGC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E2','AGGCTGGT','CACAACTA','GTTGGTCC','TCATCAAG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F2','ATGGTTAG','CATTGATA','GCAAACGC','TGCCCGCT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G2','ATAACCTA','CGGTGAGC','GATCTTAT','TCCGAGCG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H2','AACGGTCA','CCGAACTC','GGTCCAAG','TTATTGGT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A3','AAAGCATA','CTGCAGCC','GCCTTTAT','TGTAGCGG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B3','ATTGGACG','CAGCTTAC','GGCAAGGA','TCATCCTT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C3','ACGTTACA','CGTAGGTT','GACGACGG','TTACCTAC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D3','ACTTCACT','CGAAGTTG','GAGCACGC','TTCGTGAA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E3','AACAAGTC','CGGCTCCA','GTATGTAT','TCTGCAGG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F3','AGTCTGTA','CAGAATAG','GCCTCCGT','TTAGGACC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G3','ATGTCCAG','CGACGTCA','GCTATAGC','TACGAGTT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H3','ACACCTAA','CGTTTGGG','GACAAACC','TTGGGCTT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A4','AGAACGCC','CATGGCAG','GTCTTTGA','TCGCAATT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B4','AGGGACTG','CCTCTAAC','GACAGGCT','TTATCTGA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C4','ACATTGGC','CTTAGTCA','GAGCCCAT','TGCGAATG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D4','AAATCGTC','CTTCGAAT','GCGATCGG','TGCGATCA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E4','AGCTGACG','CCGGTGTC','GTAAACAT','TATCCTGA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F4','AACGACAC','CGTCCTCT','GCATGATA','TTGATGGG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G4','AGCTTCTC','CCTGCGGT','GTACAACG','TAGAGTAA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H4','ACTGGAGC','CGGTCGTG','GAAATCAA','TTCCATCT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A5','ATTGGGAA','CAGTCTGG','GGCATACT','TCACACTC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B5','ATCGTACT','CATCAGTG','GGGACTAC','TCATGCGA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C5','ATGCATTC','CACTGACT','GGTACGGG','TCAGTCAA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D5','AGACGGAT','CCTTTAGA','GTCGACTC','TAGACTCG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E5','ATCCAAGG','CCGTTGAA','GGAAGCTC','TATGCTCT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F5','AACACAGC','CGGTTTAG','GTACGGCT','TCTGACTA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G5','ATGAAGTA','CGCCGAAC','GAAGCTCG','TCTTTCGT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H5','ATAGTATG','CCGCGTCT','GGCTCCAC','TATAAGGA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A6','ACGGGACT','CTTTCGAC','GAACATGA','TGCATCTG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B6','AACGCGAA','CTATTTGG','GCGCACCT','TGTAGATC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C6','ACTCAGAC','CGCTCAGG','GAGGTTTA','TTAAGCCT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D6','ATGCCAAA','CCTTATCG','GAAGTCTT','TGCAGGGC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E6','ATTGAAAC','CAGCCCGA','GCCATTTG','TGATGGCT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F6','ATGCCGGC','CCTAATTA','GACTTCCT','TGAGGAAG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G6','AGCACTGG','CATTACAC','GTGCGACA','TCAGTGTT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H6','AAGCATAA','CCCATCGC','GGTTGATG','TTAGCGCT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A7','AGGTCATA','CTCATCAT','GCTGAGGG','TAACGTCC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B7','AGGGATGA','CTTCTGTT','GAATGCAC','TCCACACG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C7','ACACCGGG','CATAATCC','GGCGGAAT','TTGTTCTA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D7','AACTTAGA','CCGGATCC','GGTCGCAT','TTAACGTG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E7','AAGACGTG','CCATGTGT','GTTCACAA','TGCGTACC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F7','ACCCGAGA','CAAACTTT','GGTTAGAC','TTGGTCCG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G7','ATTACCGG','CAGTAATT','GCCGGTAA','TGACTGCC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H7','AACGGGTG','CTAATTCT','GCTTCAAC','TGGCACGA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A8','ATGATACG','CCACAGAA','GACTGTTC','TGTGCCGT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B8','ACGTTCAC','CAAGGTCT','GTTAAGTG','TGCCCAGA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C8','AGCTCGAG','CAGGAAGA','GCACGTTT','TTTATCCC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D8','AATCTTTG','CTCAAGAC','GGATGAGT','TCGGCCCA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E8','AGCCTATG','CTAACGCA','GCTTACAT','TAGGGTGC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F8','AGTTGGGA','CCAGAAAG','GTGCCCTC','TACATTCT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G8','AAGTACTC','CTTGGAGA','GGAACTCT','TCCCTGAG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H8','AAGAGCGG','CTTGTTAT','GGCCCATC','TCATAGCA', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A9','ACAACTTG','CTCCAACA','GAGTGCGT','TGTGTGAC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-B9','AAGCGTGT','CTTGACCG','GCCACGTA','TGATTAAC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-C9','AGATCGGT','CATCGTCG','GTCATATA','TCGGACAC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-D9','ACCTACTG','CAAGGGAC','GGGACACA','TTTCTTGT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-E9','AGTAAGCA','CCGGTAAT','GTATCTTC','TACCGCGG', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-F9','AGTTAGTT','CACGCACG','GTACTTAA','TCGAGCGC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-G9','AGTCTCAG','CAATGGCA','GCCGAAGT','TTGACTTC', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-H9','ACCTGCCA','CTTCATAC','GGAATATG','TAGGCGGT', 'dna', '10x', 'Droplet', NOW()),
('SI-NA-A10','ACAGCAAC','CGCAATTT','GAGTTGCG','TTTCGCGA','dna', '10x', 'Droplet', NOW()),
('SI-NA-B10','ACCATTAA','CTGGACGT','GAACGGTC','TGTTCACG','dna', '10x', 'Droplet', NOW()),
('SI-NA-C10','ATCTGATC','CGTGCTAA','GAGAAGGG','TCACTCCT','dna', '10x', 'Droplet', NOW()),
('SI-NA-D10','AGATAACA','CTTATTTG','GCGGGCAT','TACCCGGC','dna', '10x', 'Droplet', NOW()),
('SI-NA-E10','ATTGTTTC','CGCAGGAG','GCACCAGT','TAGTACCA','dna', '10x', 'Droplet', NOW()),
('SI-NA-F10','ATTCGTGC','CGCGTGCA','GAATACTG','TCGACAAT','dna', '10x', 'Droplet', NOW()),
('SI-NA-G10','ATACTGAG','CGGAGACT','GATGCCTC','TCCTATGA','dna', '10x', 'Droplet', NOW()),
('SI-NA-H10','ATTTCAGC','CGAGTGAT','GACCGCCA','TCGAATTG','dna', '10x', 'Droplet', NOW()),
('SI-NA-A11','ACCAGTCC','CTTTCCTT','GGACAGGG','TAGGTAAA','dna', '10x', 'Droplet', NOW()),
('SI-NA-B11','ATGGTCGC','CGACATAG','GATTCGCT','TCCAGATA','dna', '10x', 'Droplet', NOW()),
('SI-NA-C11','ACCGAACA','CGACTCTT','GTTTGTGG','TAGACGAC','dna', '10x', 'Droplet', NOW()),
('SI-NA-D11','ATATGAGA','CACCTCAG','GCTACTTC','TGGGAGCT','dna', '10x', 'Droplet', NOW()),
('SI-NA-E11','ATCGCCAT','CATAAAGG','GGGTTTCC','TCACGGTA','dna', '10x', 'Droplet', NOW()),
('SI-NA-F11','AGCAGTTA','CTTGTACC','GAACCCGG','TCGTAGAT','dna', '10x', 'Droplet', NOW()),
('SI-NA-G11','AGGGCGTT','CTATACGC','GCTCGTCA','TACATAAG','dna', '10x', 'Droplet', NOW()),
('SI-NA-H11','AGGATCGA','CACGATTC','GTATCGAG','TCTCGACT','dna', '10x', 'Droplet', NOW()),
('SI-NA-A12','ACTACTGT','CGGGAACG','GACCTCTC','TTATGGAA','dna', '10x', 'Droplet', NOW()),
('SI-NA-B12','ACGCTTGG','CGCTACAT','GAAAGACA','TTTGCGTC','dna', '10x', 'Droplet', NOW()),
('SI-NA-C12','ATCCGGCA','CCGTTATG','GGTAATGT','TAAGCCAC','dna', '10x', 'Droplet', NOW()),
('SI-NA-D12','AGAAACGT','CACTCAAC','GCTGTGTA','TTGCGTCG','dna', '10x', 'Droplet', NOW()),
('SI-NA-E12','ACGCGGAA','CGCTATCC','GTTGCATG','TAAATCGT','dna', '10x', 'Droplet', NOW()),
('SI-NA-F12','AATTGAAC','CCAGTGGA','GTCCATTG','TGGACCCT','dna', '10x', 'Droplet', NOW()),
('SI-NA-G12','ACCCGCAC','CATGCGTA','GTGATAGT','TGATATCG','dna', '10x', 'Droplet', NOW()),
('SI-NA-H12','ACGAGTAG','CAATCCCT','GTCCAGGC','TGTGTATA','dna', '10x', 'Droplet', NOW()),

('SI-TT-A1','','GTAACATGCG','','','rna','10x','Droplet',NOW()),
('SI-TT-A2','','GTGGATCAAA','','','rna','10x','Droplet',NOW()),
('SI-TT-A3','','CACTACGAAA','','','rna','10x','Droplet',NOW()),
('SI-TT-A4','','CTCTAGCGAG','','','rna','10x','Droplet',NOW()),
('SI-TT-A5','','GTAGCCCTGT','','','rna','10x','Droplet',NOW()),
('SI-TT-A6','','TAACGCGTGA','','','rna','10x','Droplet',NOW()),
('SI-TT-A7','','TCCCAAGGGT','','','rna','10x','Droplet',NOW()),
('SI-TT-A8','','CGAAGTATAC','','','rna','10x','Droplet',NOW()),
('SI-TT-A9','','AAGTGGAGAG','','','rna','10x','Droplet',NOW()),
('SI-TT-A10','','CGTGACATGC','','','rna','10x','Droplet',NOW()),
('SI-TT-A11','','CGGAACCCAA','','','rna','10x','Droplet',NOW()),
('SI-TT-A12','','CACCGCACCA','','','rna','10x','Droplet',NOW()),
('SI-TT-B1','','ACAGTAACTA','','','rna','10x','Droplet',NOW()),
('SI-TT-B2','','TCTACCATTT','','','rna','10x','Droplet',NOW()),
('SI-TT-B3','','CACGGTGAAT','','','rna','10x','Droplet',NOW()),
('SI-TT-B4','','GTAGACGAAA','','','rna','10x','Droplet',NOW()),
('SI-TT-B5','','TCGGCTCTAC','','','rna','10x','Droplet',NOW()),
('SI-TT-B6','','AATGCCATGA','','','rna','10x','Droplet',NOW()),
('SI-TT-B7','','GCCTTCGGTA','','','rna','10x','Droplet',NOW()),
('SI-TT-B8','','GCACTGAGAA','','','rna','10x','Droplet',NOW()),
('SI-TT-B9','','TATTGAGGCA','','','rna','10x','Droplet',NOW()),
('SI-TT-B10','','GCCCGATGGA','','','rna','10x','Droplet',NOW()),
('SI-TT-B11','','TCTTACTTGC','','','rna','10x','Droplet',NOW()),
('SI-TT-B12','','CGTCAAGGGC','','','rna','10x','Droplet',NOW()),
('SI-TT-C1','','TGCGCGGTTT','','','rna','10x','Droplet',NOW()),
('SI-TT-C2','','CAATCCCGAC','','','rna','10x','Droplet',NOW()),
('SI-TT-C3','','ATGGCTTGTG','','','rna','10x','Droplet',NOW()),
('SI-TT-C4','','TTCTCGATGA','','','rna','10x','Droplet',NOW()),
('SI-TT-C5','','TCCGTTGGAT','','','rna','10x','Droplet',NOW()),
('SI-TT-C6','','ACGACTACCA','','','rna','10x','Droplet',NOW()),
('SI-TT-C7','','CGCGCACTTA','','','rna','10x','Droplet',NOW()),
('SI-TT-C8','','GCTACAAAGC','','','rna','10x','Droplet',NOW()),
('SI-TT-C9','','TATCAGCCTA','','','rna','10x','Droplet',NOW()),
('SI-TT-C10','','AGAATGGTTT','','','rna','10x','Droplet',NOW()),
('SI-TT-C11','','ATGGGTGAAA','','','rna','10x','Droplet',NOW()),
('SI-TT-C12','','TCGTCAAGAT','','','rna','10x','Droplet',NOW()),
('SI-TT-D1','','TGCAATGTTC','','','rna','10x','Droplet',NOW()),
('SI-TT-D2','','TTAATACGCG','','','rna','10x','Droplet',NOW()),
('SI-TT-D3','','CCTTCTAGAG','','','rna','10x','Droplet',NOW()),
('SI-TT-D4','','GCAGTATAGG','','','rna','10x','Droplet',NOW()),
('SI-TT-D5','','TGGTTCGGGT','','','rna','10x','Droplet',NOW()),
('SI-TT-D6','','CCCAGCTTCT','','','rna','10x','Droplet',NOW()),
('SI-TT-D7','','CCTGTCAGGG','','','rna','10x','Droplet',NOW()),
('SI-TT-D8','','CGCTGAAATC','','','rna','10x','Droplet',NOW()),
('SI-TT-D9','','TGGTCCCAAG','','','rna','10x','Droplet',NOW()),
('SI-TT-D10','','ATGCGAATGG','','','rna','10x','Droplet',NOW()),
('SI-TT-D11','','CGAATATTCG','','','rna','10x','Droplet',NOW()),
('SI-TT-D12','','GAATTGGTTA','','','rna','10x','Droplet',NOW()),
('SI-TT-E1','','TTATTCGAGG','','','rna','10x','Droplet',NOW()),
('SI-TT-E2','','ATGGAGGGAG','','','rna','10x','Droplet',NOW()),
('SI-TT-E3','','ACCAGACAAC','','','rna','10x','Droplet',NOW()),
('SI-TT-E4','','AACCACGCAT','','','rna','10x','Droplet',NOW()),
('SI-TT-E5','','CGCGGTAGGT','','','rna','10x','Droplet',NOW()),
('SI-TT-E6','','TTGAGAGTCA','','','rna','10x','Droplet',NOW()),
('SI-TT-E7','','GTCCTTCGGC','','','rna','10x','Droplet',NOW()),
('SI-TT-E8','','GAGCAAGGGC','','','rna','10x','Droplet',NOW()),
('SI-TT-E9','','TGTCCCAACG','','','rna','10x','Droplet',NOW()),
('SI-TT-E10','','CACAATCCCA','','','rna','10x','Droplet',NOW()),
('SI-TT-E11','','TCCGGGACAA','','','rna','10x','Droplet',NOW()),
('SI-TT-E12','','CGTCCACCTG','','','rna','10x','Droplet',NOW()),
('SI-TT-F1','','AAGATTGGAT','','','rna','10x','Droplet',NOW()),
('SI-TT-F2','','AAGGGCCGCA','','','rna','10x','Droplet',NOW()),
('SI-TT-F3','','GAGAGGATAT','','','rna','10x','Droplet',NOW()),
('SI-TT-F4','','CCCACCACAA','','','rna','10x','Droplet',NOW()),
('SI-TT-F5','','CGGCTGGATG','','','rna','10x','Droplet',NOW()),
('SI-TT-F6','','TTGCCCGTGC','','','rna','10x','Droplet',NOW()),
('SI-TT-F7','','AATGTATCCA','','','rna','10x','Droplet',NOW()),
('SI-TT-F8','','CTCCTTTAGA','','','rna','10x','Droplet',NOW()),
('SI-TT-F9','','GTCCCATCAA','','','rna','10x','Droplet',NOW()),
('SI-TT-F10','','CCGGCAACTG','','','rna','10x','Droplet',NOW()),
('SI-TT-F11','','TTCACACCTT','','','rna','10x','Droplet',NOW()),
('SI-TT-F12','','GAGACGCACG','','','rna','10x','Droplet',NOW()),
('SI-TT-G1','','TGTAGTCATT','','','rna','10x','Droplet',NOW()),
('SI-TT-G2','','CATGTGGGTT','','','rna','10x','Droplet',NOW()),
('SI-TT-G3','','ATGACGTCGC','','','rna','10x','Droplet',NOW()),
('SI-TT-G4','','GCGCTTATGG','','','rna','10x','Droplet',NOW()),
('SI-TT-G5','','ATAGGGCGAG','','','rna','10x','Droplet',NOW()),
('SI-TT-G6','','GCGGGTAAGT','','','rna','10x','Droplet',NOW()),
('SI-TT-G7','','GTTTCACGAT','','','rna','10x','Droplet',NOW()),
('SI-TT-G8','','TAAGCAACTG','','','rna','10x','Droplet',NOW()),
('SI-TT-G9','','CCGGAGGAAG','','','rna','10x','Droplet',NOW()),
('SI-TT-G10','','ACTTTACGTG','','','rna','10x','Droplet',NOW()),
('SI-TT-G11','','GATAACCTGC','','','rna','10x','Droplet',NOW()),
('SI-TT-G12','','CTTGCATAAA','','','rna','10x','Droplet',NOW()),
('SI-TT-H1','','ACAATGTGAA','','','rna','10x','Droplet',NOW()),
('SI-TT-H2','','TAGCATAGTG','','','rna','10x','Droplet',NOW()),
('SI-TT-H3','','CCCGTTCTCG','','','rna','10x','Droplet',NOW()),
('SI-TT-H4','','AGTTTCCTGG','','','rna','10x','Droplet',NOW()),
('SI-TT-H5','','AGCAAGAAGC','','','rna','10x','Droplet',NOW()),
('SI-TT-H6','','CCTATCCTCG','','','rna','10x','Droplet',NOW()),
('SI-TT-H7','','ACCTCGAGCT','','','rna','10x','Droplet',NOW()),
('SI-TT-H8','','ATAAGGATAC','','','rna','10x','Droplet',NOW()),
('SI-TT-H9','','AGAACTTAGA','','','rna','10x','Droplet',NOW()),
('SI-TT-H10','','TTATCTAGGG','','','rna','10x','Droplet',NOW()),
('SI-TT-H11','','ACAATCGATC','','','rna','10x','Droplet',NOW()),
('SI-TT-H12','','TGATGATTCA','','','rna','10x','Droplet',NOW());