-- AlterTable
ALTER TABLE "Collaborator" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Donor" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "Specimen" ALTER COLUMN "receipt_date" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "collection_date" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "last_frozen_date" SET DATA TYPE TIMESTAMPTZ(6),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(6);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(6);
